# GitPool GitHub Pages Configuration
title: GitPool
description: Lightning-fast Git worktree management for CI/CD and development workflows
baseurl: ""
url: "https://albertywu.github.io"
github:
  repository_url: https://github.com/albertywu/gitpool
  repository_nwo: albertywu/gitpool

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Theme
remote_theme: pages-themes/midnight@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /quickstart
  - title: Documentation
    url: /docs
  - title: Examples
    url: /examples
  - title: GitHub
    url: https://github.com/albertywu/gitpool

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/